### ISSUE TITLE
✨ [Feature] Card Component

### ISSUE THREAD

**Issue by nyeoni** [manito42/FrontEnd#10]

**Comment by 9utty** [comment]
@nyeoni 여기서 만드는 중에 잠깐 의문이 든게 있어서 공유드립니다!

 ```typescript
 import React from "react";

interface Props {
  children: React.ReactNode;
}

export default function ManitoCard({ children }: Props) {
  return (
    <div
      className="rounded-xl w-full
          transition duration-300 transform border border-gray-300
          sm:scale-100
          scale-[0.8]
          sm:hover:scale-105ac
          hover:shadow-lg
          dark:border-gray-200/50"
    >
      {children}
    </div>
  );
}
```
사실 이렇게 만드는 수밖에 없는데.. 그냥 tailwind class 만들어두고 가져다가 쓰는게 더좋을 것 같은데... 음... onClick을 받자니.. 각각의 컴포넌트에서 사용한다고 했을때, 매개변수로 받아야하는 data의 타입이 각각 다를 것 같아 고민중입니다!! ㅠㅠ 흑

**Comment by 9utty** [comment]
```typescript
const openMentorModal = (data: MentorProfileDto) => {
    dispatch(CurrMentorSlice.actions.deleteMentor());
    dispatch(CurrMentorSlice.actions.setMentor(data));
    dispatch(CurrMentorSlice.actions.openMentorModal());
  };
  ```
  지금 MentorCard에서 onClick 이벤트에서 사용하는 콜백함수인데 이런 유형의 데이터를 핸들링해야하는 경우가 빈번할 것 같습니다!

**Comment by nyeoni** [comment]
Card Component 의 가장 상위 `div` 태그에 html div 관련 props 를 받도록 해서 해결하는건 어떨까용?
예를 들어, 아래의 코드와 같이 Card Component 의 나머지 props 를 가장 상위 div 태그에 넘기는 방식으로 하면 좋을 것 같습니다!
```typescript
interface CardProps extends React.HTMLProps<HTMLDivElement> {
  // 예: title?: string;
}

const Card = ({children, ...props}: CardProps) => {
  return <div {...props}>{children}</div>;
}

**Comment by nyeoni** [comment]
찾아보니 `HTMLProps` 보다 `ComponentProps<T>` 가 더 좋다고 합니다!
[참고자료](https://velog.io/@centraldogma99/HTMLAttributes-HTMLProp-%EC%9D%84-%EC%93%B0%EC%A7%80-%EB%A7%88%EC%84%B8%EC%9A%94)

**Comment by 9utty** [comment]
@nyeoni 아하! 맞네요! 그렇게 하면 되겠군요! 감사합니다 ㅋㅋㅋㅋㅋ

**Comment by nyeoni** [comment]
추가적으로 `ComponentProps` 가 더 좋은 이유를 정리하자면, `HTMLProps` 는 기본 HTML props 만 가지고오는데에 반해 `ComponentProps` 는 React 컴포넌트의 내장 props 인 key 나 ref 등의 React 컴포넌트와 기본 HTML 요소에 대한 props 를 추출해주기 때문에 더 유용하다고 합니다!
