### ISSUE TITLE
[TODO] 남은 할 일

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#118]
- 현재 홈페이지, 프로필 탐색, 프로필 변경에 관한 영역은 작업 완료
- 멘토링 예약과 관련된 부분 처리 필요 #84 
  - 멘토링 예약 요청 테이블
    - 멘토링 예약 카드
  - 멘토링 현황 페이지
    - /mentorings (?) 아니면 /reservations (?)
    - 멘토 입장 / 멘티 입장 잘 구분해서 보여줘야할듯.
    - 그리고 진행 중인 멘토링과 종료된 멘토링도 구분
    - @koreanddinghwan 이 쪽 API 관련해서 한번 이야기해봐야할 것 같음.
  - 멘토링 예약 상세 보기 모달
    - 예약에 관련된 피드백 (카드?)
  - 멘토들 피드백 모아보기(?)
    - 이건 바로 안해도 될 것 같음.

**Comment by koreanddinghwan** [comment]
> 멘토링 현황 페이지
/mentorings (?) 아니면 /reservations (?)
멘토 입장 / 멘티 입장 잘 구분해서 보여줘야할듯.
그리고 진행 중인 멘토링과 종료된 멘토링도 구분
@koreanddinghwan 이 쪽 API 관련해서 한번 이야기해봐야할 것 같음.

현재 유저의 멘토링 정보를 가져오는 API인가요?

**Comment by JuneParkCode** [comment]
@koreanddinghwan 네 맞습니다. 제 기억으로는 멘토 / 멘티는 나눠 줬던 것 같고 상태는 active 만 봤던거같네요
