### ISSUE TITLE
[Bug] 첫 접속시 멘토 리스트 로딩이 안됨

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#120]
## 문제
- 첫 접속 시에 멘토가 로딩되지 않음

## 환경
- 아이폰 / 사파리

## 추정원인
- 첫 state 가 undefined 인데, 이 때 InfinityScroll 컴포넌트 자체가 로드되지 않는 것으로 보임.

**Comment by JuneParkCode** [comment]
명확한 원인 분석 후 작업 진행 필요함

**Comment by JuneParkCode** [comment]
@koreanddinghwan @obvoso 아까 말씀하신게 이 이슈 맞죠?
@obvoso 님이 제안하신 방향으로 한번 고쳐봅시다.

**Comment by obvoso** [comment]
> @koreanddinghwan @obvoso 아까 말씀하신게 이 이슈 맞죠?
> 
> @obvoso 님이 제안하신 방향으로 한번 고쳐봅시다.

넵 맞아요 getServerSideProps로 변경해보는 거 말씀드린거예요
