### ISSUE TITLE
[UI/UX] 모달 뒤로가기 지원

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#123]
## 현재
- 모달이 띄워진 상태에서 뒤로가기 하면 아예 이전 페이지로 돌아감

## 변경
- 뒤로가기 시 모달만 내려가도록 변경
- 멘토 모달, 커넥트 모달에 적용 필요

**Comment by JuneParkCode** [comment]
@falconlee236 @obvoso @jinaji @9utty 

- 마감기한 다음주 수요일 (09.13)
- 작업하고 싶으신 분 계시면 assignee 등록 후 작업
- 오늘 (09.09) 까지 안가져가시면 제가 작업합니다. (ㅠㅠ)

**Comment by obvoso** [comment]
말씀해주신 뒤로가기가 브라우저의 뒤로가기버튼인가요??

**Comment by JuneParkCode** [comment]
@obvoso 네 맞아요~ 현재는 모달 켜진상태에서 뒤로가기(브라우저) 하면 페이지 전환되어버랴요.

**Comment by obvoso** [comment]
기한 전까지 해볼게요!
