### ISSUE TITLE
💚 [Chore] 패키지 매니저 마이그레이션

### ISSUE THREAD

**Issue by nyeoni** [manito42/FrontEnd#14]
@9utty  전에 이야기했었던 `npm` -> `yarn berry` 로 패키지매니저 마이그레이션하는거 어떻게 생각하시나용?

괜찮으시면 chromatics PR 올릴때 수정해서 같이 올리려고 합니당!

**Comment by 9utty** [comment]
좋은생각인 것 같아요! 그러면서 지금 작업하고 있는 Common을 그러니까 디자인시스템을 모노레포로 디펜던시 주고 하면 될 것 같긴한데.. 아직 그렇게 써보진 못해서 ㅋㅋㅋ

**Comment by nyeoni** [comment]
@9utty 모노레포 구축까지는 안하고, 패키지 매니저 수정한 후 `.yarn`, `yarn.lock` 만 일단 올리겠습니당! 모노레포 구축은 `berry` 쓰다가 맨 나중 테스크로 빼도 좋을것 같아용!!

**Comment by 9utty** [comment]
알겠습니다! 당장은 패키지매니저만 교체하는 느낌으로 인지하고 있겠습니다!

**Comment by nyeoni** [comment]
넵!! ㅎㅎ
