### ISSUE TITLE
[Bug] Home화면에서 card의 짧은 소개글 업데이트 안됨

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/FrontEnd#143]
https://github.com/manito42/FrontEnd/assets/76278794/32a8f048-58a2-4187-9d16-ae871d9f8ed3

- 짧은 소개글이 없도록 업데이트 후, home화면에서 보이는 짧은 소개글과 실제 짧은 소개글이 다름.

**Comment by JuneParkCode** [comment]
이거 의도된 작업입니다. 아예 빈 경우에 카드에서 'id 입니다' 를 default 로 잡혀있어요. (텅텅 비니까 보기 싫어서 그렇게 했던 것 같음)
