### ISSUE TITLE
[UI/UX] 관심분야 # trimming

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/FrontEnd#150]
- [ ] 관심분야 입력시 #NodeJS하면 NodeJS로 trimming
- [ ] profile update에서 placeholder 내용 바꾸기
- [ ] 수정완료/취소 버튼 위치 변경.

**Comment by JuneParkCode** [comment]
https://github.com/manito42/FrontEnd/blob/359640b92469a4f273eb2ef73adadd5d3f1cca0a/42manito/src/components/Profile/Update/HashtagUpdateInput.tsx#L21-L83

제출 이전 앞에 존재하는 # 트리밍
