### ISSUE TITLE
[request] 확인 버튼이 필요한가?

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/FrontEnd#155]
## 분류
- UI/UX ...

## 설명
- 확인 프로세스가 있긴한데, 생각보다 불편합니다.
- 멘토입장에서는 멘티가 확인했다는걸 알 수 있지만, 멘티입장에서는 이걸 눌러야만 하는게 여간 귀찮은 일이 아닐 수 없습니다.

- 차후에 reservations/{id} 페이지 생기면 페이지 접속하면서 확인 프로세스가 끝나게하면 멘티입장에서 더 편할 것 같습니다.

**Comment by JuneParkCode** [comment]
차라리 멘토링  시작 버튼으로 두고 백엔드에서 멘토링 시간을 기록히는 용도로 활용할까요?

**Comment by koreanddinghwan** [comment]
아뇨 저는 이 멘토링 요청에 대해 '확인했냐 안했냐'를 체크하고, 확인한 시간을 넣어서 유저가 멘토링을 취소할지말지에 대한 정보를 제공하는게 좋을 것 같아요

**Comment by JuneParkCode** [comment]
그 중간 상태가 모호해지는것 같은데 확인 후 즉시 카드의 진행중으로 보이게 되는건가요

**Comment by koreanddinghwan** [comment]
그렇게되죠

**Comment by JuneParkCode** [comment]
@falconlee236 @obvoso @jinaji 나머지 분들은 이쪽 프로세스에 대해서 어떻게 생각하시는지

**Comment by obvoso** [comment]
뮤님이 제안하시는 프로세스가 인트라 평가 프로세스랑 비슷하다고 생각되는데
인트라 생각하면, 익숙한 프로세스라 사용자한테 편할 거 같긴 해요

근데 평가랑 다르게 지금은 타임슬롯이 없어서 언제 멘토링을 할지 모르는 부분이라(언제 매칭될 지 모르니까..) "확인" 단계가 필요할 거 같기도 해요..

**Comment by jinaji** [comment]
멘티가 확인 누르는 건 확실히 불편할 수 있다고 생각되긴 해여 확인 버튼으로 교환되는 정보값이 없어서..? 
멘토가 멘토링 요청을 수락한 후에 시간이나 장소 조율 등은 외부(slack?)에서 연락이 오가게 될 것 같아서 확인 프로세스가 굳이 인 느낌도 있고여 ... (확인만 있고 취소 버튼이 없어서 그런 것 같아용)
편의성 생각하면 수락 알림이 가니 멘토 멘티 간의 조율이 잘 된다고 생각했을 때 확인 프로세스가 없어도 될 것 같고,
시간같은 게 확정되면 확인 누르는 것도 의미가 있을 것 같다 ... 가 저의 의견입니다

> 아뇨 저는 이 멘토링 요청에 대해 '확인했냐 안했냐'를 체크하고, 확인한 시간을 넣어서 유저가 멘토링을 취소할지말지에 대한 정보를 제공하는게 좋을 것 같아요

뮤님이 말씀주신 요 부분 궁금한 게 있는데 멘토링 요청 확인 시간은 멘토와 멘티 둘 다 기록되게 되는 건가여? 유저가 멘토링 취소할지 말지의 유저도 멘토와 멘티 둘 다 일지도 궁금합니다

**Comment by JuneParkCode** [comment]
멘토링 시간에 대한 정보가 필요하면 명시적으로 두고, 아니라면 reservation component 가 띄워짐과 함께 변경 처리 필요

**Comment by falconlee236** [comment]
제가 확인버튼을 만들자고 주장해서 조금만 첨언하자면
지금 프로세스가
1. 멘티가 멘토한테 멘토 신청을 한다.
2. 멘토는 멘티의 신청을 받고 수락을 누른다.
3. 멘티는 멘토가 수락한 것을 확인한다.
이 과정에서 3번이 불필요하다고 생각하신것 같습니다.
저는 시간에 대한 명시적인 정보도 필요하지만, 멘토가 멘토링을 수락한 사실을 멘티에게 한번더 확인할 수 있는 확인 과정이 필요하다고 생각합니다.

**Comment by koreanddinghwan** [comment]
아 확인버튼을 없애자는거지 확인프로세스를 없애자고 말씀드린게 아닙니다 제가 헷갈리게 말씀드렸네요. 

멘티가 자신이 신청한 멘토링 모달을 클릭하면 그 '클릭했다는 행위 === 확인'  이라고 생각해서 빼자고 말씀드린겁니다.  
네트워크 상에서 요청은 날라가게끔하구요

**Comment by JuneParkCode** [comment]
- 멘티가 멘토에게 연락을 취하도록 해야함.
- 버튼은 진행하기로 변경
  - 멘토 프로필의 정보에 링크를 첨부하도록 (슬랙 DM 링크(권장))
    - regex 로 링크 검증
- 진행하기 버튼을 클릭하면 새탭에서 해당 링크열기 / 메일로 링크 정보 전송
