### ISSUE TITLE
[bug] 홈 화면 베너 스와핑이 작동하지 않습니다.

### ISSUE THREAD

**Issue by falconlee236** [manito42/FrontEnd#156]
**버그 설명**
/home에 있는 베너가 손가락으로 좌우 스와핑이 안됩니다.
손가락으로 넘어가지지가 않고 시간이 지나면 자동으로 다음 베너로 이동합니다.

**재현 방법**
1. /home 페이지에 접속
2. 메인 베너를 왼쪽/오른쪽으로 스와핑을 합니다.
3. 위의 에러를 볼 수 있습니다.

**정상 동작**
베너를 스와핑 하면 베너가 자유롭게 넘어가야 할 것 같습니다.

**모바일 환경 정보**
 - Device: [Galaxy Note 10 5G]
 - OS: [Android 12]
 - Browser [naver whale]
 - Version [3.0.2.2]

**Comment by JuneParkCode** [comment]
버튼으로 구성했던건데 아직 반영이 되지 않아 발생하는 문제입니다

**Comment by jinaji** [comment]
스와핑은 구현되지 않은 게 맞습니다 버튼 PR 곧 머지하겠습니다!~

**Comment by JuneParkCode** [comment]
#142
