### ISSUE TITLE
[bug] 멘토 프로필->확인->리뷰 등록 시 리뷰등록 버튼 무반응

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/FrontEnd#157]
**버그 설명**
어떤 버그가 발생하는지 정확하게 기술해주세요.

**재현 방법**
재현 방법은 다음과 같이 기술합니다.
1. 대기중인 멘토링에서
2. 멘토 프로필 누르고
3. 확인버튼 누른 다음 리뷰등록이 안됨

**스크린샷**
가능하다면, 스크린샷 혹은 영상으로 버그를 보여주세요.

https://github.com/manito42/FrontEnd/assets/76278794/7f9f75b2-2cac-476e-af77-19ed08d15201

**데스크탑 환경 정보**
 - OS: [Mac M1]
 - Browser [e.g. chrome]
 - Version [버전 116.0.5845.187(공식 빌드) (arm64)]

**Comment by JuneParkCode** [comment]
대기중인 멘토링에 진행중이 있으면 안되는 상황인데 그게 문제인 것 같습니다

**Comment by JuneParkCode** [comment]
+ 홈에도 모달 추가

**Comment by JuneParkCode** [comment]
저는 구현이 안됩니다...

**Comment by JuneParkCode** [comment]
홈에서 멘토링 요청 이후 상태 변경시 발생함 
문제 원인 : 홈에서는 해당 모달 지원 안함
해결방안 1 : 요청 완료 이후 모달 닫기
