### ISSUE TITLE
[bug] 멘토 프로필 관심분야 글자수 제한 먹히지 않음

### ISSUE THREAD

**Issue by jinaji** [manito42/FrontEnd#158]
**버그 설명**
- 관심분야 글자수 제한 걸리지 않는 현상
- 길어지면 튀어나옴

**재현 방법**
재현 방법은 다음과 같이 기술합니다.
1. 프로필 페이지에 접속
2. 관심분야 글자수 (2~12) 오버되게 등록
3. 다음과 같은 에러를 볼 수 있음.

**정상 동작**
12글자 이상이면 alert 나오고 등록 안 되어야 할 것 같음.

**스크린샷**
<img width="1228" alt="스크린샷 2023-09-25 오후 1 22 26" src="https://github.com/manito42/FrontEnd/assets/101309869/cdb60b2c-a4ce-4edb-8cc7-c3835cdaee46">

**데스크탑 환경 정보**
 - OS: [Mac M1]
 - Browser [chrome]
 - Version [이거무슨버전이죠]

**추가 설명**
2글자 이하는 등록 안 됩니다

**Comment by JuneParkCode** [comment]
https://github.com/manito42/FrontEnd/blob/10dcb7072014b769422b6c9dc7fd54e160cbc1ff/42manito/src/components/Profile/Update/HashtagUpdateInput.tsx#L21-L50

이 부분 문제인데 length 체크가 잘 안되는듯..?
.length 로 판단할 경우 한글에 대해서 제대로 체크가 되지 않는 문제가 있습니다.

**Comment by jinaji** [comment]
영어랑 숫자도 넘어가여

**Comment by koreanddinghwan** [comment]
이분야는 백엔드랑도 같이 처리해야합니다.

**Comment by koreanddinghwan** [comment]
<img width="1066" alt="스크린샷 2023-09-25 15 08 26" src="https://github.com/manito42/FrontEnd/assets/76278794/6426e34a-7802-4274-a9d1-d54d02980cb6">

**Comment by koreanddinghwan** [comment]
데이터베이스: 한글/영어/숫자/이모지 모두 1개의 문자로 인식, varchar(32)는 한글/영어/숫자/이모지 32개

**Comment by koreanddinghwan** [comment]
프론트에서 이모지가 2 length차지하고, 나머지는 1length씩 차지하는거 맞나요?

**Comment by JuneParkCode** [comment]
프론트에서는 length byte 기준으로 잡았던걸로 기억합니다.
