### ISSUE TITLE
[bug] 내 카드를 클릭한 상황에서도 멘토링 요청 버튼이 노출됨

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#160]
**버그 설명**
내 프로필 카드를 누른 상황에서 멘토링 요청 버튼이 노출되며, 버튼을 클릭하고 멘토링 신청 모달까지 도달할 수 있습니다.
이후 신청은 실패합니다. (백엔드는 정상)

**재현 방법**
재현 방법은 다음과 같이 기술합니다.
1. home -> 내 카드 클릭
2. 멘토링 모달에 요청하기 버튼이 존재함

**정상 동작**
내 카드의 경우 멘토링 요청 버튼이 노출되면 안됨.

**스크린샷**
- <img width="791" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/9239ca75-4ea2-4f3b-96d9-d1f65548bc35">
-<img width="914" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/7ed559d3-f1ab-47ab-9779-440b61f0586b">

**데스크탑 환경 정보**
- OS: Mac 13.3.1 (a)
- Browser chrome
- Version [ 116.0.5845.187 (Official Build) (arm64) ]

**추가 설명**
기존에 막아뒀다고 생각했는데, 지금 제대로 안막힌거 같습니다.

**Comment by obvoso** [comment]
이부분 저도 보고 확인해보고있었는데

UserProfile 컴포넌트에서 connect버튼을 children으로 주입받고 있더라고요
주입해주는 Modal 컴포넌트랑 UserProfile컴포넌트 모두 uid를 비교하는 부분이 없는 거 같야요

기존에 막아두신 부분이 어느 컴포넌트인가요..?

꺽새가 여기서 안먹네요..

**Comment by JuneParkCode** [comment]
아 그러면 제가 변경하면서 빼먹은 것 같아요.

**Comment by JuneParkCode** [comment]
https://github.com/manito42/FrontEnd/blob/359640b92469a4f273eb2ef73adadd5d3f1cca0a/42manito/src/pages/index.tsx#L149-L158

버튼 생성 조건에 대해서 별도로 추가 필요
