### ISSUE TITLE
[request] 서치 기능이 더 드러났으면 좋겠어요

### ISSUE THREAD

**Issue by jinaji** [manito42/FrontEnd#163]
## 분류
- UI/UX ...

## 설명
- 서치 기능이 더 드러났으면 좋겠습니다
서치 기능이 메뉴 안쪽에 있어서 접근성이 떨어질 것 같아요. 멘토 프로필을 카테고리별로 묶어서 볼 수는 있지만, 인트라 아이디만 검색되는 게 아니라 카테고리나 관심분야까지 서치 되는 짱 컴포넌트라 좀 더 접근이 쉽게 만드는 게 좋겠다고 생각하는데 우떠신가요 

생각해 본 위치들은 ...
1. 메인 화면 안에 삽입
2. 헤더 로그인 로그아웃 자리에 아이콘 삽입 (이 경우 서치 페이지로 가게끔)
3. 메인 화면 카테고리 마지막에 아이콘이나 더보기, 탐색 등 ... 뭔가 더 찾아볼 수 있을 것 같은 무언가를 추가
<img width="1158" alt="스크린샷 2023-09-25 오후 2 31 32" src="https://github.com/manito42/FrontEnd/assets/101309869/91f4b7d5-174d-4fe8-97c7-aa8b7a23473b">

의견 하나씩 부탁드립니다 ~!

**Comment by JuneParkCode** [comment]
3번으로 구현할 경우에는 search 가 아래 리스트와 연관이 된다고 생각할 수도 있다는 생각이 들어서 별도로 개발 과정이 필요할 것 같고, 2번의 경우에는 모바일만 조금 신경써보면 될 것 같습니다. (모바일에서 어색해서 제외했었어요.)

**Comment by obvoso** [comment]
보통 검색이 헤더에 있으니까 추가로 넣는다면 저는 헤더가 좋을 거 같아요.
성준님이 위에서 말씀해주신 거를 고려해보면.. 모바일에서 헤더 컬럼을 2개로 잡고 서치를 2번째 컬럼에 위치하게 하면 어떠신가요...

**Comment by JuneParkCode** [comment]
search 위치의 경우 #169 에 언급된 헤더 / 사이드바 변경과 함께 이루어져야함

**Comment by falconlee236** [comment]
3번은 아래 관심분야 쪽과 관련이 있어 보이는데, 이미 관심 분야는 버튼으로 구현해 두어서 불 필요 할것 같습니다.
2번 보다는 obvoso님 말처럼 1번이 더 좋을것 같습니다. 헤더에 검색기능이 있는게 더 자연스러운것 같아요

**Comment by koreanddinghwan** [comment]
<img width="1618" alt="스크린샷 2023-10-01 15 30 00" src="https://github.com/manito42/FrontEnd/assets/76278794/5821fe59-ac10-418d-bc4d-4267be17d3d7">

**Comment by JuneParkCode** [comment]
@obvoso 님이 작업해주시는 것으로...
