### ISSUE TITLE
[bug] 멘토링 피드백 최소 별점

### ISSUE THREAD

**Issue by obvoso** [manito42/FrontEnd#165]
**버그 설명**

멘토 / 멘티 모두 별점이 0점임에도 피드백이 전송됨

**재현 방법**

1. 멘토 멘토링 종료 후 피드백 모달 오픈
2. 별점을 남길 때 별점 컴포넌트를 클릭하지 않고 피드백 전송
3. 별점이 0점임에도 정상적으로 전송

**정상 동작**
0점이면 에러 alert 처리.
폼 전송 안됨.

**스크린샷**
<img width="523" alt="스크린샷 2023-09-25 오후 3 31 07" src="https://github.com/manito42/FrontEnd/assets/97217713/d4505e7d-eb78-4755-bb1d-d5a82abbe7c6">
<img width="523" alt="스크린샷 2023-09-25 오후 3 29 39" src="https://github.com/manito42/FrontEnd/assets/97217713/a89f8233-f367-4085-8487-c6d9ef682822">

**데스크탑 환경 정보**
 - OS: [e.g. i9 mac]
 - Browser [e.g. Chrome]
 - Version [e.g. 117.0]

**추가 설명**
별점 컴포넌트를 클릭하면 최소 별점이 0.5점으로 잡히는데,
별점 컴포넌트를 클릭하지 않으면 0점으로 전송이 돼요.
피드백 작성후 서버로 전송할 때 최소 별점에 대한 검증이 따로 없는 거 같더라고요
전송 전 별점 검증이 필요할 거 같아요

**Comment by koreanddinghwan** [comment]
0점은 의도된 작업입니다

**Comment by koreanddinghwan** [comment]
근데 UX적으로 보면 유저에게 최소한 1번은 별점을 누르도록 유도해야하지않을까영

**Comment by koreanddinghwan** [comment]
리뷰만 띡 작성하고 등록하기 하면 안되니까 

1번안으로 5점을 기본값으로 주던가//
2번안으로 별점 컴포넌트를 최소한 1번은 클릭을 하도록해서 의도적이지 않게 0점주는 일이 없도록.

**Comment by JuneParkCode** [comment]
제 생각에는 5점 기본값이 조금 더 나을 것 같아요.

**Comment by falconlee236** [comment]
> 0점은 의도된 작업입니다

이렇게 되면은 의도치 않게 사람들이 그냥 리뷰 등록을 누르면 0점이 너무 많아질것 같아요.
일단 서비스적으로 5점을 받은 멘토가 많아야 생태계을 긍정적인 방향으로 생성할 수 있을것 같습니다.


> 제 생각에는 5점 기본값이 조금 더 나을 것 같아요.

이 의견에 저도 동의합니다.
