### ISSUE TITLE
[bug] profile update description 글자 수 제한

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#166]
**버그 설명**
소개글 2,000 자 제한이 되어있으나 실제로는 1,000자임 (수정 실패)

**재현 방법**
- 소개글에서 1,000자 이상 요청시 수정이 안됨 (아무런 안내가 없이 네트워크 문제)

**정상 동작**
- 1000자로 제한

**스크린샷**
-None

**데스크탑 환경 정보**
- OS: Mac 13.3.1 (a)
- Browser chrome
- Version [ 116.0.5845.187 (Official Build) (arm64) ]

**추가 설명**
- place holder, limit 변경

**Comment by falconlee236** [comment]
모바일 환경 정보

Device: [Galaxy Note 10 5G]
OS: [Android 12]
Browser [naver whale]
Version [3.0.2.2]
이 환경에서도 같은 오류 발생합니다.
