### ISSUE TITLE
[request] UI -> 헤더의 햄버거 아이콘 방향에서 사이드바가 나와야함

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#167]
## 분류
- UI/UX

## 설명
- @jinhyeop 님이 테스트해주고 있었는데, 사이드바가 햄버거랑 다른 방향에서 나오는게 어색하다고 느꼈다고 합니다. 의견 받아보고 변경해봅시다.

**Comment by obvoso** [comment]
신경쓰고 보니 어색하네요..

추가로 모바일환경(아이폰12 미니)에서 사이드바를 등장 방향 반대로 밀어 끄려고 하면 뒤로가기가 되어서 사이드 바도 꺼지고 페이지도 뒤로가져요
제 휴대폰이 작아서 사이드바가 화면에 꽉 차서 그런 거 같은데 다른 모바일환경에서는 어떤지 확인 부탁드립니다(이건 따로 이슈로 뺄까요,...?)

**Comment by jinaji** [comment]
오 신경 안 써봤는데 말 들으니 그런 것 같기도 하네용 아이콘 방향에서 나오는 것 좋습니다

제 모바일환경 (아이폰 14) 에서도 사이드 바가 화면 거의 대부분을 차지하네여 ... 빈공간 찾아서 누르기가 힘들어요 수정 ... 필요할 것 같습니다 (따로 이슈 ... 찬성이어요)

**Comment by falconlee236** [comment]
![image](https://github.com/manito42/FrontEnd/assets/52999093/99d9eade-f100-4dcd-8d01-12745ea638c0)
안드로이드 버전 12에서도 거의 대부분 차지하네요..
이전 이슈에도 있는 것 같은데 뒤로가기 버튼이 필요하거나
핸드폰에 뒤로가기 버튼을 누르면 모달이 꺼지게 만드는 것이 좋을 것 같습니다.
#138

**Comment by JuneParkCode** [comment]
햄배거 방향에서 나오게 변경

**Comment by JuneParkCode** [comment]
버튼도 함께 추가 필요합니다. (중앙 사이드에 위치하도록 변경)
