### ISSUE TITLE
[bug] 멘토링 요청 모달이 자동으로 켜지는 버그

### ISSUE THREAD

**Issue by jinaji** [manito42/FrontEnd#168]
**버그 설명**
멘토 프로필(ProfileContainer)을 띄운 후 종료하지 않고 멘토링 요청(connect modal)을 여러 번 시도한 후 프로필을 껐다가 다시 띄웠을 때 멘토링 요청 모달이 자동으로 켜집니다

**재현 방법**
1. 멘토 프로필 띄우기
2. 멘토링 요청 후 (모달 띄우기)
3. 멘토 프로필을 끄지 않고 재요청
4. 멘토 프로필 끄기
5. 다시 멘토 프로필 띄우면
6. 버그 재현

- 조건
 예약이 막히는 경우가 여러 개(alert 메세지가 다름)인데, alert 확인 버튼을 눌렀을 때 멘토링 요청 모달이 종료되는 경우에 한해서 해당 오류가 출력됩니다~! 멘토링 요청 모달이 남아있는 경우 cancel 버튼을 누르면 정상 동작 되는 걸 확인했습니다!
해당 버그 재현하시려면 이미 예약된 멘토에게 다시 멘토링 두 번 요청하시면 될 것 같아요 한 번 실행했을 때는 버그 재현 안 됩니다
alert 후에도 멘토링 요청 모달이 남아있게 하거나 / 모달 내리면서 handleFocusOut() 가 실행되면 될 것 같은데 잘은 모르겠네염

**정상 동작**
멘토링 요청 모달이 종료되었다가 다시 작동했을 때 모달이 켜지지 않아야 함

**데스크탑 환경 정보**
 - OS: [Mac M1]
 - Browser [chrome]
 - Version [??]

**Comment by JuneParkCode** [comment]
뒤로가기 + 멘토 모달 + 커넥트 모달에 대해서 함께 처리를 고민해야함.

1. 뒤로가기를 넣어야하는가?
- 모바일에서 뒤로가기 하는 상황을 고려하면 넣는 것이 좋음
- 그러나, 현재 이로 인한 문제가 같이 수반되고 있음 
2. 멘토링 신청 완료 이후 모든 modal을 닫아야하는가?

**Comment by obvoso** [comment]
https://github.com/manito42/FrontEnd/issues/171#issuecomment-1733625186
위 댓글 확인해주시고 의견 달아주시면 될 거 같아욤ㅜㅜ..

예약된 멘토에게 다시 멘토링 두 번 요청하는 동작 자체를 막는게 제일 좋을 거 같은데 성준님이 따로 이슈 남겨주신 3번에 대한 항목.. 고려해보고 수정하겠습니다

**Comment by jinaji** [comment]
위 이슈 댓글 확인했습니다
모바일 환경 고려해서 모달에서 뒤로가기 적용하신 걸로 알고 있는데, 멘토링 요청 모달은 모바일 환경 안에서 모달 종료 버튼이 완벽히 노출되는 상황이고 멘토 프로필 모달에 비해서 크기가 작아서 저에게는 팝업창 정도로 인식이 되네용
제 경우에는 (요청 모달이 페이지 단위라고 인식이 안 되는 경우) 모달 창 종료 후에 앞으로 가기로 다시 여는 일이 없을 것 같아여

멘토 프로필은 상대적으로 크기가 커서 페이지 비슷하게 인식할 수도 있을 것 같아서 뒤로가기 지원 되어도 좋을 것 같고, 요청 모달에서는 뒤로가기 빠져도 완전 OK라고 생각합니닷

멘토링 두 번 막는 것도 좋다고 생각해여 ... 근데 어떤 alert에서 같은 방식 문제가 일어날 지 모르겠어서 !.. 요 모달들 안에서도 처리가 되어야 할 것 같습니닷
