### ISSUE TITLE
[bug] mentor modal 이 닫히는 과정에서 뒤쪽 스크린 스크롤이 변경됨

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#171]
**버그 설명**
- mentor modal 을 닫기로 닫거나, 뒤로가기로 닫는 과정에서 뒤쪽 스크린의 스크롤이 최상단으로 이동한

**재현 방법**
1. 멘토 카드 클릭
2. 멘토 모달이 띄워지면 닫기 클릭
3. 이전 화면의 스크롤이 최상단으로 이동

**정상 동작**
- 최상단 이동이 아닌, 이전 위치 유지

**스크린샷**

https://github.com/manito42/FrontEnd/assets/81505228/539257f2-9717-4bf2-ae9d-7cb05f223266

**데스크탑 환경 정보**
 - OS: Mac 13.3.1 (a) 
 - Browser chrome
 - Version [ 116.0.5845.187 (Official Build) (arm64) ]

**추가 설명**
- 뒤로가기에 의해서 발생하는 문제로, 뒤로가기 기능에 대한 논의가 필요함 (넣을지 말지)

**Comment by obvoso** [comment]
문제가 아마 브라우저는 기본적으로 이전 페이지들의 scroll 좌표를 기억하고 있는데,
모달이 2개 띄워지면서 첫번째 모달 이전 좌표(홈의 좌표)를 잊어버려 스크롤이 위로 올라가는 거 같아요.

mentor modal은 뒤로가기를 지원하고, connect모달은 뒤로가기를 지원하지 않으면 해당 문제는 해결 될 거 같아요

동작 방식이

- 모달 state변경시 각각 history 관련 이벤트를 브라우저 stack에 넣을 수 있어요.
- 하지만 pop하는 과정에서 하나씩 pop이 되지 않고, 한번에 등록된 이벤트가 pop되는 동작이 계속 이루어져요
(이부분은 당시 해당 이슈 처리하면서 계속 찾아봤었는데.. 이유를 아직도 모릅니다.. 죄송해요)
- 그래서 다수의 이벤트를 스택에 쌓지 않고 useEffect로 상태가 변경되면 스택에서 이벤트를 계속 삭제, 추가 하면서 1개의 이벤트만 등록되게 했어요

그런데도 반복된 동작을 하다보면 이벤트가 꼬이는 거 같네요..ㅜㅜ 
다른분들의 의견을 들어보고
아예 뒤로가기를 빼거나, connect모달의 뒤로가기만 빼거나 하는 방향으로 수정하도록 하겠습니다

**Comment by falconlee236** [comment]
이렇게 버그가 계속 빌생하면은 모달창에 한에서는 뒤로가기를 빼야할것 같습니다 😭

**Comment by JuneParkCode** [comment]
- 뒤로가기를 제거해서 해결하는걸로 합시다.
