### ISSUE TITLE
[request] 프로필에서 해시태그 클릭시 검색으로 이동

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#172]
## 분류
- 기능 / UI

## 설명
- 프로필의 해시태그를 클릭시 search/${hashtag} 로 이동하여 다른 멘토를 볼 수 있도록 하면 더 좋을 것 같습니다.
- 구현을 위해서, 해시태그에 클릭에 대한 핸들링이 필요하며 (현재 onclick 받을 수 있음) profile update 에서 같이 확인하며 작업해야합니다.

**Comment by jinaji** [comment]
좋습니다 ~! # trim한 후에 작업하면 간단할 것 같아여

멘토링 분야 / 관심 분야 둘 다에 적용되는 건가요?
지금은 멘토링 분야는 마우스 올라갔을 때 아무 동작 없지만 관심 분야에서는 손가락으로 바뀌네용

**Comment by falconlee236** [comment]
> 좋습니다 ~! # trim한 후에 작업하면 간단할 것 같아여
> 
> 
> 
> 멘토링 분야 / 관심 분야 둘 다에 적용되는 건가요?
> 
> 지금은 멘토링 분야는 마우스 올라갔을 때 아무 동작 없지만 관심 분야에서는 손가락으로 바뀌네용

둘다 작업하면 좋을것 같은데 이것까지하면 작업량이 늘어나겠죠???

**Comment by JuneParkCode** [comment]
작업량이 많이 크지는 않은데 저 부분을 제가 초반에 작성해서 코드 구조가 이상합니다.

**Comment by koreanddinghwan** [comment]
찬성

**Comment by JuneParkCode** [comment]
cursor-pointer 로 카테고리도 같이 /search/:{tag} 로 넘기도록 변경

**Comment by JuneParkCode** [comment]
- #191
