### ISSUE TITLE
[request] 모달 상태 변경 이후 모달 종료

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#173]
## 분류
- UI/UX

## 설명
- 멘토링 상태 변경, 예약 상태 변경 이후 띄워진 모달을 모두 닫게하는게 나을 것 같습니다.
- 이로 인한 문제들이 몇 가지가 발생하고 있고, 이미 작업이 완료된 상태에서 더 이상 모달을 볼 이유가 사라져 유저가 할 일이 더 늘어나는 것이 아닌가? 하는 의견을 들었습니다.
- 다 닫지 않았던 이유는, 그래도 프로필 한번 더 볼까 싶어 남겼었는데, 다른 분들의 생각은 어떠신가요?

**Comment by obvoso** [comment]
제가 느끼기에는 모달 상태 변경 후 모달이 안꺼지는 게 ux적으로 좋다고 느꼈었는데..
side effect가 많은 거 같아서 배포시에는 꺼지게 하고, 배포 후 다시 수정하는 방향으로 가면 좋을 거 같아요.....ㅠ,,,,
다른분들이 그렇게 안느끼신다면 그냥 계속 모달을 꺼지게 하는 것도 좋습니다!!

**Comment by falconlee236** [comment]
저는 반대로 모달이 꺼지는게 좋다고 생각합니다.
버그때문이 아니라 확인이나 수락을 했을때 완료라는 느낌을 주기 위해서는 모달창이 내려가는 것이 좋은것 같아요

**Comment by JuneParkCode** [comment]
안끄고 상태관리 해소하는걸로 해결
