### ISSUE TITLE
[request] 멘토링 요청 <->멘토프로필에서 카테고리와 해시태그 구분

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/FrontEnd#178]
## 분류

-  UI/UX ...

## 설명

- 하나로 통일해야합니다.

<img width="529" alt="스크린샷 2023-09-25 19 12 59" src="https://github.com/manito42/FrontEnd/assets/76278794/24e95d84-9764-4dc0-bbe4-919c8194482d">

<img width="435" alt="스크린샷 2023-09-25 19 13 14" src="https://github.com/manito42/FrontEnd/assets/76278794/590bee65-eab4-4604-87f8-85e845e813eb">

**Comment by JuneParkCode** [comment]
https://github.com/manito42/FrontEnd/blob/359640b92469a4f273eb2ef73adadd5d3f1cca0a/42manito/src/components/Connect/ConnectModal.tsx#L55-L72

카테고리 -> 멘토링 분야
