### ISSUE TITLE
[request]멘토링 취소 요청시 사유 작성 추가

### ISSUE THREAD

**Issue by obvoso** [manito42/FrontEnd#180]
## 분류
- UI/UX

## 설명
- 멘토링 요청 후 멘토가 취소할 때 취소 사유를 작성하는 거 어떤가요..?

<img width="523" alt="스크린샷 2023-09-25 오후 7 34 17" src="https://github.com/manito42/FrontEnd/assets/97217713/aca67672-2804-4a42-a621-37335ddc0a8c">

- 취소 메일이 위와 같이 와서 (요청 메세지가 멘티가 작성한 메세지로 전달됨)
사용자입장에서는 조금 불편할 거 같습니다..

**Comment by JuneParkCode** [comment]
@koreanddinghwan

**Comment by koreanddinghwan** [comment]
백엔드 DTO바꾸고, 템플릿 수정만하면 가능합니당

**Comment by koreanddinghwan** [comment]
괜찮나요? 모달 수정하셔야할텐데

**Comment by JuneParkCode** [comment]
cancel 모달 하나 추가해야해요.

**Comment by JuneParkCode** [comment]
근데 그렇게 어렵지는 않을듯... feedback modal 내부 요소만 조금 수정하면 됩니다.

그 과정에서 작은 모달 스타일 컴포넌트를 공통으로 하나 만들어야할 것 같긴하네요.

**Comment by jinaji** [comment]
취소 사유 추가 좋습니다~! 
작은 모달 스타일 컴포넌트. .. 있으면 너무 좋지요 따봉

**Comment by falconlee236** [comment]
취소할때는 그래도 사유가 있어야 한다고 생각했는데 그 점을 잘 짚어주신것 같습니다

**Comment by JuneParkCode** [comment]
취소사유 추가하는걸로.
-- 백엔드 이슈에서 정리

**Comment by JuneParkCode** [comment]
프론트의 경우 feedback 모달같이 누르면 됨

**Comment by JuneParkCode** [comment]
@koreanddinghwan 백엔드 멘토링 취소 프로세스 이슈 정리 부탁드립니다!!

**Comment by koreanddinghwan** [comment]
- 취소 사유와 관련해 database 영속화를 할건지 말건지 결정해야합니다.
- 취소 사유와 관련해 몇 글자까지 지원할건지 결정해야합니다.

**Comment by koreanddinghwan** [comment]
> @koreanddinghwan 백엔드 멘토링 취소 프로세스 이슈 정리 부탁드립니다!!

취소 자체는 기존과 같이 REQUEST 상태에서는 멘토/멘티 모두 취소가능하며
ACCEPT/MENTEE_CHECKED 상태에서는 멘토만 가능합니다.

**Comment by koreanddinghwan** [comment]
> * 취소 사유와 관련해 database 영속화를 할건지 말건지 결정해야합니다.
> * 취소 사유와 관련해 몇 글자까지 지원할건지 결정해야합니다.

100글자 정도면 괜찮을 것 같은데, 괜찮으신가요

**Comment by koreanddinghwan** [comment]
manito42/backend/issues/116
