### ISSUE TITLE
[bug] 오탈자

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/FrontEnd#183]
**버그 설명**
<img width="531" alt="스크린샷 2023-09-25 19 48 31" src="https://github.com/manito42/FrontEnd/assets/76278794/a8622e8f-9b18-4f71-a858-8ee10f2e5a68">

**추가 설명**
해당 버그에 대해서 추가로 기술할 내용에 대해 작성해주세요.

**Comment by JuneParkCode** [comment]
https://github.com/manito42/FrontEnd/blob/359640b92469a4f273eb2ef73adadd5d3f1cca0a/42manito/src/components/Reservation/Reservation.tsx#L107-L112

오탈자 수정
