### ISSUE TITLE
[bug] 모달 끄는 이벤트 모달 아래 클릭시 적용안됨

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/FrontEnd#184]
**버그 설명**
- 모달 내려가야하는데 안내려감

**재현 방법**
재현 방법은 다음과 같이 기술합니다.
1. 프로필페이지
2. 모달 아래 빈공간 클릭

**정상 동작**
- 모달이 내려가야함.

**스크린샷**

<img width="970" alt="스크린샷 2023-09-25 20 03 04" src="https://github.com/manito42/FrontEnd/assets/76278794/4350ed6b-1657-425e-b6b6-b89ec58de0d0">

**데스크탑 환경 정보**
 - OS: [e.g. Mac]
 - Browser [e.g. chrome]

**Comment by JuneParkCode** [comment]
이거 고민을 많이 해봤던건데 저는 해결방안을 찾지 못해서 수정을 못했었습니다...
처리 가능한분 헬프 ㅠ

**Comment by JuneParkCode** [comment]
https://github.com/manito42/FrontEnd/blob/359640b92469a4f273eb2ef73adadd5d3f1cca0a/42manito/src/styles/mentor.css#L49-L51

h-fit 추가하면 해결됩니다!!!
