### ISSUE TITLE
[request] About 페이지에서 텍스트가 부자연스럽습니다.

### ISSUE THREAD

**Issue by falconlee236** [manito42/FrontEnd#188]
## 분류
수정사항

## 설명
About page에서 No man lives alone 텍스트가 나오고나서 42 manito 텍스트가 나오는데,
이 42manito 텍스트가 No man lives alone 이후 부자연스럽게 나오는 것 같습니다.

웹 환경에서는 괜찮은것 같은데 모바일 환경에서는 좀 부자연스럽네요

모바일 환경 정보

Device: [Galaxy Note 10 5G]
OS: [Android 12]
Browser [naver whale]
Version [3.0.2.2]

![image](https://github.com/manito42/FrontEnd/assets/52999093/25fefed1-1e31-43c6-80ac-4d4932e1d3ed)

**Comment by jinaji** [comment]
말씀하신 부자연스러움이 가로로 배치되어있다가 세로로 내려가는 형태 ..? 인가요? 뭔가 뚝 끊기는 느낌이 드는 것 같기도 하네여!!

**Comment by falconlee236** [comment]
> 말씀하신 부자연스러움이 가로로 배치되어있다가 세로로 내려가는 형태 ..? 인가요? 뭔가 뚝 끊기는 느낌이 드는 것 같기도 하네여!!

넵 맞습니다 웹에서는 부자연스러움이 안느껴지는데 앱에서는 확실히 느껴지는것 같습니다

**Comment by koreanddinghwan** [comment]
아마 이 페이지는 배포하면서  사라질 것 같아요

@JuneParkCode

**Comment by JuneParkCode** [comment]
없에는걸로 합시다.
