### ISSUE TITLE
[request] 모바일 환경에서 멘토 모달창이 너무 큰것 같습니다.

### ISSUE THREAD

**Issue by falconlee236** [manito42/FrontEnd#189]
## 분류
UI/UX

## 설명
모바일 환경에서 멘토 모달 창이 너무 커서 멘토 모달 창 밖을 누르기가 힘듭니다.
모달은 모달 밖을 누르면 자동으로 닫혀야 하는데, 모바일에서는 너무 창이 커서 여백이 너무 적은 것 같습니다.

Device: [Galaxy Note 10 5G]
OS: [Android 12]
Browser [naver whale]
Version [3.0.2.2]

![image](https://github.com/manito42/FrontEnd/assets/52999093/f6447f33-f84c-46f8-8353-28584ff5d564)

**Comment by JuneParkCode** [comment]
의도되었으며 닫기가 그래서 아래에 있읍니다

**Comment by falconlee236** [comment]
약간 화면이 작은 핸드폰 같은 경우는 저 모달창을 끄기위해서 밑으로 내려야하는 불필요한 소요가 있는것같습니다.
모달창을 약간만 작게 해서 모든 핸드폰이 한 화면에 닫기 버튼이 위치해있으면 좋겠다고 생각하는데 어떻게 생각하시나요??
@JuneParkCode

**Comment by JuneParkCode** [comment]
가능하긴 한데, 모달의 크기를 줄이는 방향보다는 닫기 버튼을 상위에 하나 두는게 조금더 낫지 않을까... 하는게 제 의견입니다.

**Comment by JuneParkCode** [comment]
뒤로가 문제 논의 후 진행

**Comment by JuneParkCode** [comment]
나중에 이야기 다시 나오면 작업하는걸로 보류
