### ISSUE TITLE
[todo] About 제거

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#192]
## 분류
- fix

## 목표
- About 페이지를 제거합니다.
- #188 

## 기한
- 23.10.03

## 할 일
- [x] About 페이지를 사이드바에서 제거
- [x] About 페이지 관련 요소 프로젝트에서 제거

## 추가 설명
- 관련되어있는 요소들이 소스에서 제거되도록 해야합니다.

**Comment by falconlee236** [comment]
이거 제가 해봐도 괜찮을까요? 뭐라도 도움이 되고 싶습니다

**Comment by JuneParkCode** [comment]
굿~~~ 다른것도 맘껏 가져가세용~~
