### ISSUE TITLE
[bug] 해시태그 짤림

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/FrontEnd#228]
**버그 설명**
home에서 멘토프로필에 해시태그가 짤립니다.

**스크린샷**
가능하다면, 스크린샷 혹은 영상으로 버그를 보여주세요.
<img width="365" alt="Screen Shot 2023-10-01 at 9 41 42 PM" src="https://github.com/manito42/FrontEnd/assets/76278794/4ff1cd4a-f769-446d-906d-e942d90463f4">

**데스크탑 환경 정보**
- cluster imac
- chrome

**Comment by JuneParkCode** [comment]
눈물이나요
