### ISSUE TITLE
[bug] 취소하기 버튼이 동작하지 않습니다

### ISSUE THREAD

**Issue by falconlee236** [manito42/FrontEnd#234]
**버그 설명**
멘토링을 신청하고 나서 취소하기 버튼을 누르면
잘못된 요청입니다 alert가 뜬 이후, 취소에 실패했다는 alert가 발생합니다.

**재현 방법**
1. home에 접속
2. 아무 멘토를 클릭해서 멘토링 신청
3. 대기중인 멘토링에서 멘토 예약 모달을 띄움
4. 취소하기 버튼을 누르면 해당 버그 발생

**정상 동작**
취소하기 버튼을 누르면 멘토링이 취소되어야 합니다.
(이제 제가 만들 취소 모달이 곧 떠야합니다)

**스크린샷**
<img width="1438" alt="image" src="https://github.com/manito42/FrontEnd/assets/52999093/4da1d114-f96d-42ca-bb2d-27b04ef01fd2">
<img width="1438" alt="image" src="https://github.com/manito42/FrontEnd/assets/52999093/617edb8d-562f-420f-b8aa-8e6a88ffa8c4">
![image](https://github.com/manito42/FrontEnd/assets/52999093/b2b085a6-0f88-481f-b9ba-dcb1b8b14d22)

**데스크탑 환경 정보**
 - OS: Mac OS ventura 13.5.2(22G91)
 - Browser: chrome

**추가 설명**
단순한 인트라 문제일 수도 있어서 일단 성준님만 assign 했습니다.

**Comment by koreanddinghwan** [comment]
저희 취소하기 사유 넣기로하지 않았나요

https://github.com/manito42/FrontEnd/issues/180

**Comment by koreanddinghwan** [comment]
<img width="969" alt="스크린샷 2023-10-02 21 18 59" src="https://github.com/manito42/FrontEnd/assets/76278794/00b2f205-edd4-4535-a79b-a7df0bbc77bc">

**Comment by koreanddinghwan** [comment]
<img width="552" alt="Screen Shot 2023-10-02 at 9 30 02 PM" src="https://github.com/manito42/FrontEnd/assets/76278794/4fb88035-3d94-476d-8707-161f85ed1135">

취소사유 넣으면 잘 처리됩니다~!~! 400에러는 대부분 body/query/param 값을 잘못넣었을때 발생합니당

**Comment by JuneParkCode** [comment]
선생님이 취소 모달을 통해서 처리를 하셔야하는 부분입니다...

**Comment by koreanddinghwan** [comment]
api docs 보게쉽게 github page로 자동배포하게 만들어두겠슴다

**Comment by falconlee236** [comment]
> 선생님이 취소 모달을 통해서 처리를 하셔야하는 부분입니다...

기존에는 그냥 취소되는걸로 알고있었는데..
제가 잘못 이해하고 있었네요

그럼
1. 취소하기 버튼을 누르면 미리 정해둔 text or 사용자 입력을 받는 모달을 띄운다
2. 해당 text를 서버에 patch 를 시켜서 완료한다.

이렇게 작업을 하면 될것같습니다.
혹시 잘못된거 있거나 추가해야할거 있으면 댓글 남겨주세요
많이 부족해서 질문이 많은점 죄송합니다 😭

**Comment by JuneParkCode** [comment]
넵 맞아요.
