### ISSUE TITLE
[request] 관심분야에 대한 추가 설명  필요

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#250]
## 분류
- 제안

## 설명
- 관심 분야에 대해서 제대로 설정이 되지 않는다는 느낌이 있습니다.
- 멘토링 신청 시 관심 분야를 선택해야하는데 해당 부분이 잘 표현이 되지 않습니다.
  - 세부 분야 / 카드 상 본인 표현 태그를 나눠서 봐야할지 고민해봐야합니다.
- 멘토링 분야 -> 세부 분야로 설정을 하는 것이 조금 더 좋을까요? 아니면 ProfileUpdate 에서 해당 칼럼에 대한 추가 설명..?

**Comment by JuneParkCode** [comment]
@falconlee236 @koreanddinghwan @9utty @obvoso @jinaji

**Comment by falconlee236** [comment]
제가 생각한 관심분야는 멘토링도 결국 사람간 대화니까 친해질수있는 하나의 매개체로써 동작하는 기능이라고 생각했습니다.

멘티가 멘토를 컨택할때 그냥 개발 멘토가 아닌, 서로 공유할수있는 관심분야를 보면서 수월한 멘토링이 가능할수있을거라 기대했습니다.

결국 성준님이 말씀하신
> 세부분야/카드상 본인표현 태그를 나눠서 봐야한다. 

는의견에 동의합니다.

관심분야는 멘토링 예약페이지에 그냥 두고, 멘토링 요청할때는 관심분야는 빼두고, 멘토링분야를 누르면 그에 세부분야를 관심분야가 있는 자리에 채우면 어떨까 합니다

**Comment by obvoso** [comment]
profile update 칼럼에 추가설명으로 예시를 적어두는 건 어떤가여?
그럼 2줄이 되긴 하는데 제일 직관적인 방법이라 생각됩니다..

**Comment by jinaji** [comment]
> profile update 칼럼에 추가설명으로 예시를 적어두는 건 어떤가여?
> 그럼 2줄이 되긴 하는데 제일 직관적인 방법이라 생각됩니다..

저도 이게 제일 나아보여여 ... 신청자들이 선택할 수 있는 항목이 됩니다 같은 느낌으로? 그렇게 되면 관심분야와 신청할 때 선택할 수 있는 세부분야로 나눠지는 게 맞는 것 같기도 하고여 🥺

**Comment by JuneParkCode** [comment]
> 관심분야는 멘토링 예약페이지에 그냥 두고, 멘토링 요청할때는 관심분야는 빼두고, 멘토링분야를 누르면 그에 세부분야를 관심분야가 있는 자리에 채우면 어떨까 합니다

이게 잘이해안되는데 다시 설명해주실 수 있을까요?

**Comment by JuneParkCode** [comment]
그리고 다들 세부 분야가 5개 제한이 아닌 10~15개로 늘리는건 어떻게 생각하시나요?

**Comment by falconlee236** [comment]
> > 관심분야는 멘토링 예약페이지에 그냥 두고, 멘토링 요청할때는 관심분야는 빼두고, 멘토링분야를 누르면 그에 세부분야를 관심분야가 있는 자리에 채우면 어떨까 합니다
> 
> 이게 잘이해안되는데 다시 설명해주실 수 있을까요?

멘토링 예약 페이지에서 멘토링 요청하기 버튼을 누르면 요청 페이지가 나옵니다.
이때 예약 페이지에서는 관심 분야는 그대로 둡니다.
그리고 요청 페이지는 관심 분야 항목을 빼고, 그 자리에 세부 분야 항목을 넣으면 좋을 것 같다는 의견 입니다.

> 그리고 다들 세부 분야가 5개 제한이 아닌 10~15개로 늘리는건 어떻게 생각하시나요?  

이 경우는 너무 많을때는 멘토링 예약 페이지가 너무 번잡할 것 같습니다.. 5개가 적당하지 않을까요

**Comment by obvoso** [comment]
> 그리고 다들 세부 분야가 5개 제한이 아닌 10~15개로 늘리는건 어떻게 생각하시나요?

멘토링분야를 대분류로 잡아서 10-15개로 늘려도 좋다고 생각해여!!

**Comment by JuneParkCode** [comment]
@falconlee236 관심분야 === 세부분야라면 세부분야로 통일하는게 좋을 것 같아요

**Comment by falconlee236** [comment]
> @falconlee236 관심분야 === 세부분야라면 세부분야로 통일하는게 좋을 것 같아요

저도 동의합니다!! 이야기해보니까 의견이 하나로 모인 것 같네요

**Comment by JuneParkCode** [comment]
관심분야에 한 줄 추가하는 것보다 멘토링 세부 분야로 따로 명시하는걸로 해결가능할 것 같아요.

**Comment by JuneParkCode** [comment]
@koreanddinghwan @falconlee236 @9utty @obvoso @jinaji 

관심분야 -> 세부분야 관련해서 다른 의견 있으신가요?

현재 제가 고려하고 있는건 다음과 같습니다.

1. 카드에 나타나는 해시태그들과 세부 분야가 서로 잘 구분되지 않음
-> 예를 들어 카드에서는 "커피챗" 이라는 태그를 보여주고 싶은데, 세부분야에 AWS, Flutter, ... 를 넣다보면 노출되지 않음
1-2. 카드에 노출되는 태그를 임의로 설정할 수 있게 하는 것이 나을까?
-> 세부 분야는 DB 상에 직접 연결되도록 하고, 노출되는 태그를 별도로 string[] 로 저장한다던가.. .하는 방법. (DB 수정 필요함)

2. 유저가 세부 분야를 멘토링에서 선택할 때 혼동이 있는 것 같음
-> 이는 "관심 분야" 라고 작성된 면에서 발생하는 문제로 보임. 처음에 "세부 분야" 에 대한 설명이 더 필요할 것 같음.
(?)아이콘을 통해서 이게 뭘 하는지 작게 보여줄 수 있다면 좋지 않을까?


[해결안]
1. 단순하게 세부 분야로 변경, 세부 분야 밑에 어떤 항목인지 설명
2. 1 + 카드 해시태그 추가 (이후 서비스 변경에서도 생각해볼 필요 있음..)
3. 다른 좋은 방안

**Comment by obvoso** [comment]
1. 카드에 노출되는 태그를 사용자에게 선택할 수 있게 하더라도, 
카드 크기가 크지 않아서 긴 태그일 경우 안보일 수도 있다고 생각합니다.. 
또 사용자에게 요구하는 게 하나 추가된다는 것 때문에.., 괜찮을까여..?

2. 세부분야로 변경하고, 어떤 항목인지 설명은 말씀에 동의합니다!

**Comment by falconlee236** [comment]
지금 카드에서 더 추가하는건 정보가 너무 과다한거 같아서.. 관심분야를 세부분야로만 변경하는게 좋을거 같아요

저는 세부분야라고 이름을 바꾸면 따로 설명이 필요하지않을것 같습니다.
혼동이 온 이유는 관심분야가 무엇인지 헷갈려서 그런건데, 세부분야이면 다 알지않을까요?

**Comment by JuneParkCode** [comment]
그러면 세부분야 변경 -> 항목 설명으로 결정합시다~
