### ISSUE TITLE
[request] social link 로 인해 유입이 더딥니다.

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#254]
## 분류
- 제안

## 설명
- 슬랙 프로필 링크 접근이 모바일에서 불가능합니다. 이로인해 사용자의 접근이 어렵습니다.
  - 실제로 사용자가 불편하다는 의견이 계속 나오고 있습니다.
  - 또한 슬랙 프로필 이동시 웹에서 로그인이 필요한데, 모바일 / 웹 환경 모두 불편하다는 의견이 있습니다.
- 실시간 사용자 모니터링 결과 50% 내외의 인원이 모바일 환경에서 접근하고 있습니다.
- 그러나, 멘토 프로필 활성화를 위한 슬랙 프로필 접근이 불가능하여 모바일에서 멘토 프로필 활성화가 어렵습니다.
- 따라서, social link 에 대해서 재고해볼 필요가 있습니다.
- social link 에 대해서 별도로 다른 수단을 허용하거나, optional 하게 처리해야할 것 같습니다. 좋은 의견 있으면 부탁드립니다.

@falconlee236 @koreanddinghwan @9utty @obvoso @jinaji

**Comment by falconlee236** [comment]
모바일은 링크가 전혀 동작하니까 불편할수 있는데, 웹은 어떤 이유로 사용자가 불편함을 느끼고있나요?

제가 실제로 웹에서 사용했을때는 멘토 프로필 확인하기로 슬랙 들어갔을때 로그인정도는 별로 불편하지 않았거든요

Social link가 불편한 근본적인 이유가 멘토 프로필을 확인하고싶다는 것이면, 슬랙 링크와 멘토링예약 페이지와는 다른 별도의 프로필이 필요해 보입니다.

프로필에는 어떤 요소가 들어가면좋을지는 생각해보겠습니다.

**Comment by obvoso** [comment]
실 시용자들이 불편함을 느낀다면, 없애는 것도 좋을 거 같아요.
슬랙 이외에 말이 나왔었던 카카오톡, 인스타 모두 링크 이동시 로그인이 필요한 건 마찬가지라....

social link가, 멘토 - 멘티 사이의 연락 수단을 제공하기 위함인데
멘토, 멘티 모두 불편함을 느낀다면 직접 슬랙으로 연락하게끔 유도하는 건 어떤가요..?
메일에 social link 대신 @000님에게 슬랙으로 연락해보세요 같은,, 문장 추가라던가 ㅜㅜ

**Comment by jinaji** [comment]
저도 요거 고민이 많았는데 ... 입력 란은 두되 필수 조건에서 빼고 수님이 말씀해주신 것처럼 누구님께 연락해보세요 메세지 남기는 것이 좋아보입니다 TT 소셜 링크가 있다면 진행 과정에서 이동여부 묻는 거랑 (현행유지) 메일에 소셜링크 항목 추가하는 것도 괜찮을 것 같기도 하고 ... 
편의성 위해 추가한 건데 유입을 막는다면 옵셔널하게 바꾸는 것도 좋을 것 같습니다 멘토 프로필 활성화 시킬 때 필수가 아니게 하는 등으로여 ...

**Comment by JuneParkCode** [comment]
@falconlee236 웹의 경우, 프로필을 찾는 과정도 문제지만 멘티가 멘토 슬랙 프로필 열 때 웹에서 슬랙이 로그인되어있어야합니다.
그런데, 이 과정에서 2FA 요구하기도 해서, 결과적으로 보면 그냥 "아직 연락이 안닿으셨나요? 슬랙에서 000 님에게 메시지를 보내주세요" 라는 메시지보다 너무 복잡합니다.

**Comment by JuneParkCode** [comment]
@obvoso @jinaji  그러면 이 의견 반영해서 수락하기 이후 / 진행하기 이후 에 메시지를 그냥 띄우는걸로 해볼까요?

**Comment by falconlee236** [comment]
> @obvoso @jinaji 그러면 이 의견 반영해서 수락하기 이후 / 진행하기 이후 에 메시지를 그냥 띄우는걸로 해볼까요?

저도 이 의견에 동의합니다. 간단하게 띄우는 대신에
그래도 개발한 기능이 있으니까.. 그건 jinaji 님 의견처럼 옵셔널하게 두는 것이 좋을 것 같습니다.
반드시 진행하기할때 띄우는것 말고, 아이콘 클릭하면 슬랙 프로필 페이지로 이동하는 식은 어떨까요?
