### ISSUE TITLE
[todo] Social Link 기능 변경

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#256]
## 분류
- fix

## 목표
- Social Link 가 Slack Profile 필수로 되어있는데 이를 Optional 하게 처리하고, 존재하는 유저에 대해서만 연결합니다.
- 존재하지 않는 유저의 경우 연결이 가능하도록 만듭니다.

## 기한
- 10.16

## 할 일
- [ ] Social link 필수 제약 변경
- [ ] 진행하기에서 Social link 가 존재하지 않을 경우, 안내를 해줍니다.

## 추가 설명
- 안내 메시지 관련 협의 필요

**Comment by JuneParkCode** [comment]
https://github.com/manito42/FrontEnd/issues/254

안내 메시지 관련해서 어떻게 처리하는게 좋을까요? 그래도 진행하기 프로세스 넘어가면서 메시지 하나정도는 모달로 띄워주는 것이 좋을 것 같아요.

**Comment by koreanddinghwan** [comment]
<img width="670" alt="스크린샷 2023-10-11 10 23 05" src="https://github.com/manito42/FrontEnd/assets/76278794/09f2a2e0-3815-4888-aa0f-bd1d3f31cff5">

여기서 모달을을 띄우신다는 말씀이신가용

**Comment by obvoso** [comment]
멘토의 프로필 수정에서가 아니라 
멘티가 진행하기를 눌렀을 때에 관해서 말씀주신 거 맞으신가요??

**Comment by JuneParkCode** [comment]
송민님이 말씀해주신게 맞아여

**Comment by koreanddinghwan** [comment]
그러면 socialLink가 ''인 경우에 intra profile로 이동하게하면 안되나요?

**Comment by JuneParkCode** [comment]
흠 그것도 나쁘지 않은 것 같네용...

**Comment by koreanddinghwan** [comment]
<img width="728" alt="스크린샷 2023-10-11 11 02 35" src="https://github.com/manito42/FrontEnd/assets/76278794/3428a028-42db-47bd-ad66-2a1a56a22841">

**Comment by obvoso** [comment]
모달 띄우고 이동 좋은 거 같아여

**Comment by JuneParkCode** [comment]
저거 중앙 정렬이안돼있었네요.. .할 때 같이해야겟읍니다.

**Comment by jinaji** [comment]
저도 모달 띄우고 이동 좋구 인트라 페이지 이동 좋습니다
그러면 작업 건은 소셜링크가 비었을 때 인트라 페이지로 이동하는 거랑 중앙정렬 (작은화면에서 해서 몰랐어여 ... 죄송합니닷) 만 하면 되는 거지용?

**Comment by JuneParkCode** [comment]
넵 좋아유

**Comment by falconlee236** [comment]
> 그러면 socialLink가 ''인 경우에 intra profile로 이동하게하면 안되나요?

42 내부 서비스니까 intra는 다들 접속할 수 있을 것 같아서 슬랙에서 발생하는 문제는 조금 해결이 가능할 것 같네요
이렇게 진행하면 좋을 것 같습니다!

**Comment by JuneParkCode** [comment]
근데 슬랙으로 이동합니다 대신 다른 멘트가 필요할 것 같아요

**Comment by JuneParkCode** [comment]
@jinaji 혹시 이거 작업하시면서 #258 #257  같이 작업가능하신가여? 작은 내용이라서 한 사람이 한꺼번에하면 좋을 것 같아요.

**Comment by jinaji** [comment]
웁스 지금 확인했네여 ... 다른 이슈들! 알겠습니다 ~~ 
슬랙으로 이동합니다 대신 다른 멘트 혹시 생각하신 거 있으실까용 ??
