### ISSUE TITLE
[hotfix] Main 화면에서 밑으로 스크롤할 때 버그 발생

### ISSUE THREAD

**Issue by falconlee236** [manito42/FrontEnd#32]
<img width="1434" alt="image" src="https://github.com/manito42/FrontEnd/assets/52999093/71405e5b-897d-4d25-9503-13c62ea0fe2e">
사이트의 메인 페이지에서 스크롤을 내리려고 하면 __알 수 없는 오류가 발생했습니다.__ 라는 메시지와 함께  
메인 페이지의 애니메이션과 같은 일부 기능이 작동하지 않는것 같습니다.

**Comment by 9utty** [comment]
@falconlee236 환경변수가 설정안되어서 데이터를 못 받아서 500번 에러 만나서 그럴 수 있습니다!

**Comment by falconlee236** [comment]
환경변수는 제가 임의로 설정하면 되나요??
아직 구조 파악 중이라서 좀 더 알아보겠습니다
@9utty

**Comment by falconlee236** [comment]
xhr.js:251     GET http://localhost:3000/undefined/home?take=12&page=0 404 (Not Found)
계속 보고 있는데, 404 에러가 나오네요?? 이것도 환경 변수 문제인지 궁금합니다 ㅠㅠㅠ
@9utty

**Comment by falconlee236** [comment]
해결 했습니다!!
next.js의 환경변수때문에 발생한 문제이고, 자세한 내용은 다음 링크를 통해 공부할 수 있을 것 같습니다.
자세한 설명 감사합니다.
[https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables](url)
[https://curryyou.tistory.com/503](url)
