### ISSUE TITLE
[Request] Footer SNS 링크 변경

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#43]
## Description
- Footer 에 필요없는 SNS 아이콘 링크를 제거하고 Github 아이콘과 저희 Organization link 를 달아주셨으면 합니다.

## Screenshot
<img width="245" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/5658c268-f48c-4d35-a32a-8e428e52d72b">

**Comment by obvoso** [comment]
이거 지금 작업해도 되는건가요?

**Comment by JuneParkCode** [comment]
> 이거 지금 작업해도 되는건가요?

넵 작업하셔도 됩니다
