### ISSUE TITLE
[Bug] MentorProfile list 우측 라인이 반짝임

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#50]
## Description
- 멘토 프로필 리스트 띄워져있는 곳에서 우측에 라인이 반짝반짝 합니다. ??
- #42 이 문제랑 연관된 것 같습니다. 스크롤 이후에 발생하네요.

## Screenshot
https://github.com/manito42/FrontEnd/assets/81505228/c2945041-e2ea-4abf-9e99-7c54c734a81a

**Comment by 9utty** [comment]
@JuneParkCode 모달 무한스크롤 안되는 문제 fix 후에 merge하고 나서도 생기는지 체크해봐야할 것 같습니다!
