### ISSUE TITLE
[Bug] 공개하기

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/FrontEnd#52]
**Describe the bug**

- 공개하기 변경한 이후에 페이지 refresh시, 원래대로 돌아감

**To Reproduce**

1. 로그인
2. 프로필
3. 공개하기 버튼 클릭
4. Refresh

**Expected behavior**

공개하기 상태가 바뀌어야함.

**Screenshots**

- 실제로 불러온 데이터는 isHide가 False인 상태.
<img width="330" alt="Screen Shot 2023-08-31 at 3 13 27 PM" src="https://github.com/manito42/FrontEnd/assets/76278794/7144743c-b6fa-456d-a8a6-a37a6a60a998">

**Comment by JuneParkCode** [comment]
새로고침시 이전 상태 불러오기는 되나, 이번에는 버튼 클릭시 상태 변경이 안되는 상태입니다.
@9utty
