### ISSUE TITLE
[Bug] ? Profile 수정시 카테고리 중앙 정렬

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#56]
## Description
- Figma
<img width="583" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/e3006de3-a920-4926-ae3f-ed45ac0688db">

- 실제
<img width="1505" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/7cb95684-d6af-44e3-ade4-81b37f1d926c">

## Comment
의도한 디자인과 달리 사진이 가운데로 안모이고 옆으로 뻗칩니다.
뭔가 불편하다고 느낀 부분이 이거 때문인 것 같습니다.
그리고 사용을 하다보니, 완료하기 버튼이 우측 상단보다는 소개글 우측 하단에 위치하는게 편하지 않을까? 하는 생각이 드는데, 해당 부분은 논의를 한번 해보고 추후 적용을 해보면 좋을 것 같습니다.

**Comment by JuneParkCode** [comment]
태그 방식으로 적용하신다면 해당 이슈 닫아주셔도 됩니다. @9utty

**Comment by 9utty** [comment]
@JuneParkCode 태그형식으로 작업을 진행 후에 이슈랑 같이 걸어서 merge하면서 close하겠습니다!
