### ISSUE TITLE
[UI/UX] Profile 관련해서 제 생각대로 고쳐봤습니다.

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#78]
## 변경사항
- Profile Category 토글 형태로 변경할 수 있음.
- Hashtag 를 Enter key 통해서 넣을 수 있음
- mobile 환경을 위해 해시태그 리스트 스크롤 가능
- 가로가 전체 확장되는 형태가 아닌, 일정 사이즈로 제한
- 짧은 소개글을 아이디 아래로 내려 자신을 표현하는 간단한 글로 사용
- 수정하기, 공개하기 위치 변경
- Description 내 URL 링크 치환
- 기타 자잘한 버그
  - 해시태그 리스트가 아래로 정렬되는 문제 수정
  - 해시태그 입력칸에서 개행이 들어가는 문제 수정
  - 프로필 이미지 모바일에서 중앙정렬 안되는 문제 해결
  - 해시태그가 mobile 환경에서 텍스트가 개행되고, 너무 큰 문제 해결

## 참고
- https://github.com/manito42/FrontEnd/tree/profile/sungjpar
- f255fee46ef045ee5b7f0c30068cbdf41277e1ef
- d0d184f1e87a8362e98ca77d9515946073cc2bc5
- 일단 구현을 하는데 집중해서 잘못된 부분이 있을 수 있음

## 시연
https://github.com/manito42/FrontEnd/assets/81505228/20a70882-1543-42b0-9eca-666a7b948fd6

https://github.com/manito42/FrontEnd/assets/81505228/b6d946d5-c072-46f7-8ea6-b118b6d70a64

## +@
- ProfileUpdate 에서 수정 취소 버튼도 하나 있으면 좋을 것 같습니다.
- 추가로, Mentor 상세보기를 계속 보고 있는데 쓰다보니 조금 UI/UX 적으로 문제가 있는 것 같습니다.
- 사진이 위쪽에 둥 뜨면서 스크롤 내릴때도 어색해지고, PC에서 필요한 정보가 다 안보입니다.
- modal 에서 이미지를 모달 프레임 안쪽으로 넣는 시도를 해봤는데, 이렇게 하면 적당하게 보이는 것 같습니다.
- connect 버튼도 마찬가지로, 우측 상단이 아닌 아예 둥둥 떠다니거나, 중앙 상단 혹은 중앙 하단에 위치하는게 UX적으로 나을 것 같습니다.

**Comment by JuneParkCode** [comment]
@9utty @koreanddinghwan

**Comment by koreanddinghwan** [comment]
## 건의사항

- 모바일 환경에서 카테고리 위아래 정렬

<img width="199" alt="스크린샷 2023-09-01 17 06 44" src="https://github.com/manito42/FrontEnd/assets/76278794/97256b4f-ebad-44bc-9fc3-816d5c54a032">

**Comment by koreanddinghwan** [comment]
작업하신거 관련 이슈들 태그 걸어주실 수 있나요 중복작업 안하게끔

**Comment by JuneParkCode** [comment]
넵 이슈 걸어두겠습니다

**Comment by JuneParkCode** [comment]
- #72 
- #56 
- #58 
- #51 
- #47

**Comment by JuneParkCode** [comment]
> ## 건의사항
> * 모바일 환경에서 카테고리 위아래 정렬
> 
> <img alt="스크린샷 2023-09-01 17 06 44" width="199" src="https://user-images.githubusercontent.com/76278794/264962426-97256b4f-ebad-44bc-9fc3-816d5c54a032.png">

<img width="224" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/36ba11d8-7cf8-4eb3-9fe8-78a76db6c9d2">


52365816a79236ad05d019499bd5f3a59d71f61b

**Comment by 9utty** [comment]
@JuneParkCode 자네 혹시 프론트할 생각 없나?
